''' https://www.practicepython.org/ 
Create a program that will play the “cows and bulls” game with the user. The game works like this:
Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that 
the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly 
in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes 
throughout teh game and tell the user at the end.
Say the number generated by the computer is 1038. An example interaction could look like this:
  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1250
  1 cow, 1 bull
  ...
Until the user guesses the number.
'''
import random

def cowsandbulls(c,u):
  print(''.join(c), "\n", ''.join(u), "\n")
  cow = bull = 0
  for i,char in enumerate(u):
    if char in c:
      print(c, "\n", u, i, cow, "\n") 
      if u[i] == c[i-cow]:
        c.pop(i-cow)
        cow += 1
      else:
        if char != u[c.index(char)+cow]:
          bull += 1
  return "cow-{} bull-{}".format(cow,bull)


def main():
  c0 = [chc for chc in str(random.randint(1000,9999))]
  while True:
    print("Od nowa {}".format(''.join(c0)))
    u0 = [chu for chu in input("Enter a number: ")]
    if c0 == u0:
      print("You won")
      break
    else:
      print(cowsandbulls(c0,u0))


if __name__ == "__main__":
  main()
