''' https://www.practicepython.org/ 
Create a program that will play the “cows and bulls” game with the user. The game works like this:
Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that 
the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly 
in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes 
throughout teh game and tell the user at the end.
Say the number generated by the computer is 1038. An example interaction could look like this:
  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1250
  1 cow, 1 bull
  ...
Until the user guesses the number.
'''
import random

def cowsandbulls(c,u):
  c = [chc for chc in c]
  u = [chu for chu in u]
  print("\n ", ''.join(c), "\n", ''.join(u), "\n")
  cow = bull = 0
  for i,char in enumerate(u): 
    if char in c: #check if users number are in random 
      print(c, "\n", u, i, cow, bull, "\n") 
      if u[i] == c[i-cow]: # check if numbers on same positions are the same - mean cow
        c.pop(i-cow) # pop cow, to avoid that sibling (second same) will be counted as bull while first were matched as cow
        cow += 1
        print("cow")
      else:
        print("enter to bull, idx in c {}".format(c.index(char)))
        if char != u[c.index(char)+cow]:
          bull += 1
          print("bull, idx in c {}".format(c.index(char)))
  return "cow-{} bull-{}".format(cow,bull)


def main():
  c0 = str(random.randint(1000,9999)) #random for guessing as a list
  while True:
    print("Od nowa {}".format(''.join(c0)))
    u0 = input("Enter a number: ") #users guess
    if c0 == u0:  
      print("You won")
      break
    else:
      print(cowsandbulls(c0,u0)) # call function to count cows&bulls


if __name__ == "__main__":
  main()
